version: "3"
services:
  database:
    image: postgres:latest
    container_name: ${DATABASE_HOST}
    user: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  postgres-data: