spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

poster:
  directory: c/Users/Public/posters

screen:
  maxScreenNumber: 16

session:
  maxFreshDays: 3