spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html

poster:
  directory: C:\Users\Public\new_posters

screen:
  maxScreenNumber: 16

session:
  maxFreshDays: 3
  cleaningTimeInMinutes: 30

security:
  jwt:
    secretKey: superDuper39Secret
    expiresMs:
      # 30 minutes
      accessToken: 1 800 000
      # in days
      refreshToken: 30