openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: localhost
    url: http://localhost:8080
info:
  version: "1.0.0"
  title: Online cinema API
  description: Project made for VSU
  contact:
    name: Anastasiya Sashina
    email: yaninastya2010@yandex.ru

paths:

  # ----------------------------------------------------------------------
  #                                 movie
  # ----------------------------------------------------------------------

  /movie/:
    get:
      tags:
        - Movie
      description: Returns all movies in pages
      parameters:
        - in: query
          name: pageNumber
          schema:
            type: integer
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            default: 5
        - in: query
          name: title
          schema:
            type: string
        - in: query
          name: sort
          schema:
            $ref: '#/components/schemas/MovieSort'
        - in: query
          name: isAsc
          schema:
            type: boolean
            default: true
      responses:
        200:
          description: Returns all movies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paging'
        400:
          description: Invalid query params
          content:
            application/json:
              schema:
                type: string
    post:
      tags:
        - Movie
      description: Creates movie
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MovieRequest'
      responses:
        201:
          description: Movie was successfully created
        400:
          description: Invalid requestBody
          content:
            application/json:
              schema:
                type: string

  /movie/{id}:
    get:
      tags:
        - Movie
      description: Gets movie info by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Movie was successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResponse'
        400:
          description: Invalid id type
          content:
            application/json:
              schema:
                type: string
        404:
          description: Movie with following id does not exist
          content:
            application/json:
              schema:
                type: string
    delete:
      tags:
        - Movie
      description: Deletes movie by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        204:
          description: Movie was successfully deleted
        400:
          description: Invalid id type
          content:
            application/json:
              schema:
                type: string
    put:
      tags:
        - Movie
      description: Updates movie by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MovieRequest'
      responses:
        200:
          description: Movie was successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResponse'
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                type: string
        404:
          description: Movie with following id does not exist
          content:
            application/json:
              schema:
                type: string
        409:
          description: Cannot be updated due to conflict
          content:
            application/json:
              schema:
                type: string

  /movie/{id}/poster:
    get:
      tags:
        - Movie
      description: Gets movie's poster by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Movie's poster was successfully fetched
          content:
            image/png:
              schema:
                type: string
                format: binary
        400:
          description: Invalid id type
          content:
            application/json:
              schema:
                type: string
        404:
          description: Movie with following id does not exist
          content:
            application/json:
              schema:
                type: string

  /movie/{id}/sessions:
    get:
      tags:
        - Movie
      description: Gets sessions for specific movie
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
        - in: query
          name: pageNumber
          schema:
            type: integer
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            default: 5
      responses:
        200:
          description: Shows all sessions for certain movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paging'
        400:
          description: Invalid id type
          content:
            application/json:
              schema:
                type: string

  # ----------------------------------------------------------------------
  #                                 screen
  # ----------------------------------------------------------------------

  /screen/:
    get:
      tags:
        - Screen
      description: Returns all screens in pages
      parameters:
        - in: query
          name: pageNumber
          schema:
            type: integer
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            default: 5
      responses:
        200:
          description: Returns all screens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paging'
        400:
          description: Invalid query params
          content:
            application/json:
              schema:
                type: string
    post:
      tags:
        - Screen
      description: Creates screen with seats and seat plan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScreenRequest'
      responses:
        201:
          description: Screen was successfully created
        400:
          description: Invalid requestBody
          content:
            application/json:
              schema:
                type: string
        405:
          description: Max number of screens was reached
          content:
            application/json:
              schema:
                type: string

  /screen/{id}:
    get:
      tags:
        - Screen
      description: Gets screen info by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Screen was successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenResponse'
        400:
          description: Invalid id type
          content:
            application/json:
              schema:
                type: string
        404:
          description: Screen with following id does not exist
          content:
            application/json:
              schema:
                type: string

  # ----------------------------------------------------------------------
  #                                 session
  # ----------------------------------------------------------------------

  /session/:
    get:
      tags:
        - Session
      description: Returns all sessions in pages
      parameters:
        - in: query
          name: pageNumber
          schema:
            type: integer
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            default: 5
      responses:
        200:
          description: Returns all sessions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paging'
        400:
          description: Invalid query params
          content:
            application/json:
              schema:
                type: string
    post:
      tags:
        - Session
      description: Creates session
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionRequest'
      responses:
        201:
          description: Session was successfully created
        400:
          description: Invalid requestBody
          content:
            application/json:
              schema:
                type: string
        409:
          description: Conflict with previous sessions
          content:
            application/json:
              schema:
                type: string

  /session/{id}:
    get:
      tags:
        - Session
      description: Gets session info by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: Session was successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        400:
          description: Invalid id type
          content:
            application/json:
              schema:
                type: string
        404:
          description: Session with following id does not exist
          content:
            application/json:
              schema:
                type: string
    delete:
      tags:
        - Session
      description: Deletes session by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        204:
          description: Session was successfully deleted
        400:
          description: Invalid id type
          content:
            application/json:
              schema:
                type: string
    put:
      tags:
        - Session
      description: Updates session by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionRequest'
      responses:
        200:
          description: Session was successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                type: string
        404:
          description: Session with following id does not exist
          content:
            application/json:
              schema:
                type: string
        409:
          description: Conflict with previous sessions
          content:
            application/json:
              schema:
                type: string

# ----------------------------------------------------------------------

components:
  schemas:
    MovieSort:
      type: object
      properties:
        sort:
          type: string
          enum: [ BY_TITLE, BY_RATING, BY_DURATION ]

    Paging:
      type: object
      properties:
        paging:
          type: object
          properties:
            pageNumber:
              type: integer
            pageSize:
              type: integer
            totalPages:
              type: integer
        data:
          type: array
          items:
            type: object

    MovieRequest:
      type: object
      properties:
        description:
          type: string
          nullable: false
        duration:
          type: string
          format: time
          example: "HH:mm"
        title:
          type: string
          nullable: false
        poster:
          type: string
          format: binary

    MovieResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        duration:
          type: string
          format: time
          example: "HH:mm"
        title:
          type: string
        rating:
          type: number
          format: double

    ScreenRequest:
      type: object
      properties:
        rows:
          type: integer
          nullable: false
          minimum: 1
          maximum: 16
        seats:
          type: integer
          nullable: false
          minimum: 1
          maximum: 20

    ScreenResponse:
      type: object
      properties:
        screenId:
          type: integer
          format: int64
        screenNumber:
          type: integer
        rows:
          type: integer
        seats:
          type: integer
        seatsSet:
          type: array
          items:
            $ref: '#/components/schemas/SeatDTO'

    SeatDTO:
      type: object
      properties:
        seatId:
          type: integer
          format: int64
        row:
          type: integer
        seatNumber:
          type: integer

    SessionRequest:
      type: object
      properties:
        screenId:
          type: integer
          format: int64
          nullable: false
        movieId:
          type: integer
          format: int64
          nullable: false
        startDate:
          type: string
          format: date
          example: "dd.MM.yyyy"
          nullable: false
        startTime:
          type: string
          format: time
          example: "HH:mm"
          nullable: false
        price:
          type: integer
          minimum: 200
          maximum: 1500
          nullable: false

    SessionResponse:
      type: object
      properties:
        sessionId:
          type: integer
          format: int64
        startTime:
          type: string
          format: date-time
          example: "dd.MM.yyyy HH:mm"
        endTime:
          type: string
          format: date-time
          example: "dd.MM.yyyy HH:mm"
        price:
          type: integer
        screen:
          $ref: '#/components/schemas/ScreenResponse'
        movie:
          $ref: '#/components/schemas/MovieResponse'
        seatPlan:
          type: array
          items:
            $ref: '#/components/schemas/SeatPlanDTO'

    SeatPlanDTO:
      type: object
      properties:
        seatPlanForSessionId:
          type: integer
          format: int64
        seat:
          $ref: '#/components/schemas/SeatDTO'
        isAvailable:
          type: boolean