CREATE TABLE IF NOT EXISTS seat
(
    seat_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id   BIGINT REFERENCES screen (screen_id) ON DELETE CASCADE NOT NULL,
    row         INTEGER                                                NOT NULL,
    seat_number INTEGER                                                NOT NULL
);