CREATE TABLE IF NOT EXISTS user_info
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) UNIQUE NOT NULL,
    name          VARCHAR(100)        NOT NULL,
    surname       VARCHAR(100)        NOT NULL,
    password_hash VARCHAR(255)        NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS email_index_user ON user_info(email);