CREATE TABLE IF NOT EXISTS seat_plan_for_session
(
    seat_plan_for_session BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session               BIGINT REFERENCES session (session_id) ON DELETE CASCADE NOT NULL,
    seat_id               BIGINT REFERENCES seat (seat_id) ON DELETE CASCADE       NOT NULL,
    is_available          BOOLEAN DEFAULT TRUE                                     NOT NULL
);